name: GitHub Action Audit

on:
  workflow_dispatch:
    inputs:
      action_url:
        description: GitHub action to audit
        required: true
        type: string

jobs:

  # SEMGREP
  # -------

  SemGrep:
    runs-on: ubuntu-latest
    steps:
      - name: Clone action
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone ${{ inputs.action_url }} ./action

      - name: Install SemGrep
        shell: bash
        run: |
          python3 -m pip install semgrep

      - name: Run SemGrep Scan
        shell: bash
        run: |
          semgrep scan --config auto ./action

  # TRIVY
  # -----

  Trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone action
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone ${{ inputs.action_url }} ./action

      - name: Install Trivy
        shell: bash
        run: |
          sudo apt install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install trivy
          trivy --version

      - name: Run Filesystem Scan
        shell: bash
        run: |
          trivy fs \
            --quiet \
            --no-progress \
            --security-checks vuln,secret,config \
            --ignore-unfixed \
            ./action

      - name: Check Dockerfile presence
        id: check_dockerfile_presence
        shell: bash
        run: |
          if [ -f "./action/Dockerfile" ]; then
            echo "dockerfile_presence=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run Container Scan
        if: ${{ steps.check_dockerfile_presence.outputs.dockerfile_presence == 'true' }}
        shell: bash
        run: |
          docker build -t action:current ./action
          trivy image \
            --quiet \
            --no-progress \
            --security-checks vuln,secret,config \
            --ignore-unfixed \
            --severity HIGH,CRITICAL \
            action:current

